---
name: "Text2Image"
version: "1.0.2"
slug: "text2image"
description: "Renders HTML to JPG images using Playwright."
url: "https://github.com/aydarik/text2image"
startup: application
arch:
  - aarch64
  - amd64
ports:
  8000/tcp: 8000
options: {}
schema: {}
image: "ghcr.io/aydarik/text2image"
