name: "GeekMagic Text2Image"
version: "1.0.0"
slug: "geek_magic_text2image"
description: "Renders HTML to JPG images for GeekMagic devices using Playwright."
url: "https://github.com/aydarik/text2image"
startup: application
arch:
  - aarch64
  - amd64
ports:
  8000/tcp: 8000
options: {}
schema: {}
image: "ghcr.io/aydarik/geek_magic_text2image:{arch}"
